name: validate msp-service
on:
  push:
    paths:
      - "msp-service/src/**/*.js"
      - "msp-service/package*.json"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./msp-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests w/ coverage
        run: npm run test:coverage
      - name: LINTing
        run: npm run test:lint
      # - name: OpenAPI Schema
      #   run: npm run test:schema
      - name: Build step
        run: npm run build