name: validate bcsc-service
on:
  push:
    branches:
      - "*"
    # paths:
    #   - "bcsc-service/src/**/*.js"
    #   - "bcsc-service/package*.json"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./bcsc-service

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: "10"
      - name: Install dependencies
        run: npm ci
      - name: Unit tests w/ coverage
        run: npm run test:coverage
      - name: LINTing
        run: npm run test:lint
      # - name: OpenAPI Schema
      #   run: npm run test:schema
      - name: Build step
        run: npm run build
